name = "cosmocrow/escrow-aiken"
version = "1.0.0"
compiler = "v1.1.9"
plutus = "v2"
license = "MIT"
description = "CardanoScrow - Multi-signature escrow smart contract for Cardano"

[repository]
user = "cosmocrow"
project = "escrow-aiken"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[config]
